# Generated by Django 2.2 on 2019-04-23 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_game', '0002_post_lovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
